name: Preview SDKs

on:
  pull_request:
    paths:
      - "fern/**"
      - "openapi.json"
      - "openapi-overrides.yml"

jobs:
  preview-typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate Preview
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --api api  --group ts-sdk --preview --log-level debug

      - name: Compile
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          cd fern/apis/api/.preview/fern-typescript-node-sdk
          yarn install
          yarn build

  preview-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Preview Python SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --api api  --group python-sdk --preview --log-level debug

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Bootstrap poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Compile
        run: |
          cd fern/apis/api/.preview/fern-python-sdk
          poetry install          
          poetry run mypy .

  preview-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Preview Go SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --api api --group go-sdk --preview --log-level debug

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Compile
        run: |
          cd fern/apis/api/.preview/fern-go-sdk
          go mod tidy
          go build ./...


  preview-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Preview C# SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --api api --group csharp-sdk --preview --log-level debug

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Compile
        run: |
          cd fern/apis/api/.preview/fern-csharp-sdk
          dotnet restore
          dotnet build

  preview-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Preview Java SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --api api --group java-sdk --preview --log-level debug

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile
        run: |
          cd fern/apis/api/.preview/fern-java-sdk
          ./gradlew build