name: Release Java SDK

on:
  workflow_call:
    inputs:
      makePR:
        description: Make Pull Request
        default: false
        type: boolean          
      version:
        description: "The version of the C# SDK that you would like to release"
        required: true
        type: string    
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Java SDK that you would like to release"
        required: true
        type: string
      makePR:
        description: Make Pull Request
        required: true
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Release Java SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          if ${{ github.event.inputs.makePR }}; then
            fern generate --group java-sdk --version ${{ inputs.version }} --mode pull-request --log-level debug
          else
            fern generate --group java-sdk --version ${{ inputs.version }} --log-level debug
          fi