name: Release PHP SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the PHP SDK that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Fern
        run: npm install -g fern-api

      - name: Release PHP SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group php-sdk --version ${{ inputs.version }} --log-level debug
