name: Index docs

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  index:
    name: Index Documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install CLI
        run: npm install -g @team-plain/cli@latest

      - name: Index Documents
        run: plain index-sitemap https://docs.vapi.ai/sitemap.xml --labelTypeIds lt_01G0EZ1XTM37C643SQTDNXR1
        env:
          PLAIN_API_KEY: ${{ secrets.PLAIN_API_KEY }}
